# Generated by Django 2.2.5 on 2020-11-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201105_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='users',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user', to='users.UserGroup'),
        ),
    ]
