# Generated by Django 2.2.5 on 2020-11-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_auto_20201105_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='key',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
